# Site settings
title: Max Spero
email: mmspero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Studying artificial intelligence at Stanford. Fascinated with art. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.maxspero.com" # the base hostname & protocol for your site
github_username:  maxspero
linkedin_username: maxspero

# Build settings
markdown: kramdown
permalink: pretty
